version: '3.7'

services:
  web:
    container_name: ecommerce-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 3000:3000
    restart: always
    environment:
      - RAILS_ENV=production
    depends_on:
      - db
      - redis

  db:
    container_name: postgres
    image: postgres:12.8
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: ecommerce_api
      POSTGRES_PASSWORD: ecommerce_api
      POSTGRES_DB: ecommerce_api

#  redis:
#    container_name: redis
#    image: redis:6.2
#    ports:
#      - 6379:6379
#    restart: always